### ISSUE TITLE
Don’t default to computing a graph for the whole area if no area is selected.  

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#153]
Interestingly, someone else suggested defaulting to the whole area. This could be problematic for large areas but we should be able to provide values calculated with the data is loaded.

**Comment by Zodiase** [comment]
A workaround is to pre-calculate the results for the whole area.

The behavior this issue is targeting is the result from the "continuity" feature where the "focus boundary", as I call it, is carried over from discover tab to map view tab and then graph view tab. To be accurate, it's not selecting the whole area by default; if you open the workspace page without the "focus boundary" parameter, the graph view tab won't have a "focus boundary" thus won't load anything. But if you do specify a boundary in the discover tab and then head to the graph view, the boundary will get carried over per the "continuity" feature specification.

**Comment by kintigh** [comment]
I think we decided this was not an issue as if there is no are selected, it doesn't try to compute the graph.  however, we need to change the label to "...select a point **or area**..."

**Comment by Zodiase** [comment]
Closed because this is the current behavior. (That is unless an area is selected due to continuity)
