### ISSUE TITLE
On graph view page change "bound" to "range +" or "range -".

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#161]
For chart data, call this just Upper and Lower or Upper Uncertainty and Lower Uncertainty.  “Bound” says to me this is the highest or lowest value it could possibly be, which is not the case.

Appropriate labels could be returned as part of the timeseries response.

**Comment by Zodiase** [comment]
Does it really make sense to say a value 1300 has an "upper uncertainty" of 1400?

**Comment by abrin** [comment]
change to "range"

**Comment by Zodiase** [comment]
![image](https://user-images.githubusercontent.com/1815174/39607601-79a10adc-4f01-11e8-8349-a0cf4c80ceef.png)

**Comment by tmcphillips** [comment]
We may want to revisit this issue to clarify (to users) exactly what we mean by an uncertainty range, and how we can refer most clearly to the upper and lower limits of the range.  For example, if what we are talking about is a _confidence interval_, then 'upper bound' and 'lower bound' are not unusual terms for referring to the upper and lower limits of the interval.  

As one example of the use of the terms 'upper bound' and 'lower bound' in a simple web-based application see this calculator:  [Confidence interval for a mean](http://www.sample-size.net/confidence-interval-mean/).

**Comment by Zodiase** [comment]
> we need to discuss further what we mean by 'uncertainty' and decide what to call the ends of the ranges displayed around the values in the plots.

@tmcphillips I'd suggest opening an new issue for this since this issue (at least as the title suggests) was about a simple UI tweak, for that moment.

I regret not recalling this change when I was implementing the graph with Plotly. Their demo I referenced by was using `Upper Bound` and I didn't notice the issue (and apparently so did the people who have checked out the CodePen demo and said nothing).

**Comment by Zodiase** [comment]
Feature is deployed in `v0.1.27`.
