### ISSUE TITLE
Put BETA (and maybe a version  number in the app header.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#185]

**Comment by abrin** [comment]
See email

**Comment by Zodiase** [comment]
@abrin Thanks!

Though it's a bit tricky to get it work nicely with the current layout. I could shift the logo towards right a bit but that would make the non-beta version have too much white space on the left.

![image](https://user-images.githubusercontent.com/1815174/39945185-2d3bd59e-552f-11e8-86e3-e7e44df4a615.png)

Here's another version:
 
![image](https://user-images.githubusercontent.com/1815174/39945150-0636f47e-552f-11e8-812d-e34c4b340435.png)

@kintigh Which one do you prefer? Also, is it fine keeping the version hidden inside that menu or do you also want it out?

**Comment by kintigh** [comment]
I would go for the first one with the green stripe. But move over the Skope. We can always move it back later. In any case, I think we eventually want to use the logo instead of the text. Suggesting putting the text there was just to make it quick and easy to get something there as we get up and running.
Keith

____________________________________
Keith W. Kintigh, Professor    kintigh@asu.edu
School of Human Evolution & Social Change
Center for Archaeology & Society, Co-director
Arizona State University, Box 872402
Tempe, AZ 85287-2402

Sent from my T-Mobile OnePlus3T

________________________________

**Comment by kintigh** [comment]
Fine to leave the version where it is.

____________________________________
Keith W. Kintigh, Professor    kintigh@asu.edu
School of Human Evolution & Social Change
Center for Archaeology & Society, Co-director
Arizona State University, Box 872402
Tempe, AZ 85287-2402

Sent from my T-Mobile OnePlus3T

________________________________

**Comment by Zodiase** [comment]
Resolved by #188.

**Comment by Zodiase** [comment]
@jterstriep needs to update the app configs to enable the beta sign.

```JSON
{
    "public": {
        "showBetaSign": true,
        ...
    },
    ...
}
```

**Comment by Zodiase** [comment]
Created dedicated deployment issue: https://github.com/openskope/skope-deployment/pull/32
