### ISSUE TITLE
Contact link doesn't work.

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#195]
Keith report that "Contact option still does not work for me in Chrom/Win10/Outlook"

This is something that difficult to test because users can have all kinds of different systems. Do we have a sense of that will work? Is there any way to have a fallback?

**Comment by kintigh** [comment]
It now pops up an Outlook window but the to: address is mailto://kintigh@asu.edu (invalid) instead of kintigh@asu.edu.  The Subject is &body= instead of some text.

**Comment by jterstriep** [comment]
Thanks. I misunderstood the configuration. I'll fix that.

**Comment by Zodiase** [comment]
Should be fixed by now.

**Comment by Zodiase** [comment]
@jterstriep I assume you reopened this because Keith wants a subject (even though it's not exactly what this issue is about)?

@kintigh What do you think would be a good subject?

**Comment by kintigh** [comment]
SKOPE App Query/Comment

**Comment by Zodiase** [comment]
@jterstriep The above commit adds the subject field. Are there anything else left for this issue?

**Comment by Zodiase** [comment]
@kintigh The highlighted text shows a commit referencing this issue. It contains changes that should resolve the empty subject issue.

![image](https://user-images.githubusercontent.com/1815174/40513512-9a062bca-5f6b-11e8-9bda-cd210726d9d1.png)

These commits will trigger DockerHub to build new images of this app (with the latest code at the time of commit) and tag the image with `latest`. When the building is done, Jeff's script can then pull the latest image to staging, after which you would be able to see the changes from these commits revealed. DockerHub is a free service so they really take their time doing the builds. From my observation a single build would take anywhere from 30 to 60 minutes, obviously depending on how busy their servers are. They also enforce delays in-between builds so, for example, two consecutive triggers would likely cause the last build to finish in 150 minutes or more. So I try to push changes less frequently to avoid clogging the build pipeline with too many unnecessary builds. 

Anyone can check the automated build status here: https://hub.docker.com/r/openskope/webapp/builds/

On the other hand, I'm also doing manual builds on my computer for each of the new versions, mainly because in some cases it could be faster than DockerHub and so you'd be able to see the results faster. However while it's building I basically can't do much else on my computer so I can't do it for every commit. I try to batch the commits into reasonable chunks and then bump the version and then do a manual build of that new version.

Either way it takes a bit of time until the changes can be reflected on the staging server.

**Comment by Zodiase** [comment]
Anyway the change should be reflected in version `0.1.20`, if not earlier (from the automated builds).
