### ISSUE TITLE
Display the charts in a pop-up window

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#3]
Pros: users can resize the pop-up window anyway they want, to make them overlap or not.
Cons: pop-ups might be blocked by the browser, so some checking and hints could be helpful UX-wise.

Notes:

- You can actually name the pop-up window so you reuse it later instead of opening new ones every time.

**Comment by jterstriep** [comment]
Can pop-up windows be coordinated with the main window? I.e. the move to the front of the browser window when the browser window brought to the front, they minimize when the browser window is minimized, etc.

**Comment by Zodiase** [comment]
@jterstriep There is this [`Visibility API`](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) that can send events when the page becomes visible or vice versa. Demo here: http://daniemon.com/tech/webapps/page-visibility/

**Comment by Zodiase** [comment]
Demo CodePen here: https://codepen.io/Zodiase/pen/rwoEQp

**Comment by Piotrek605** [comment]
Implemented on workspace/28580fe8a5a62beababb9ef2354fe7b2fa7cff90, however there are several issues:
- the window isn't actually minimized, it's just moved out of the screen
- when the window is restored, it's resized and repositioned to the original values because to constantly keep track of its dimensions and position requires knowing when the user manually minimizes it and that's difficult and adds a lot of complexity

**Comment by Piotrek605** [comment]
Just noticed that the popup window only minimizes when you switch from the main window to another tab, not when you minimize the main window, so looks like 'ifVisible' is not working correctly.

**Comment by Zodiase** [comment]
Resolved in #20.
